### ISSUE TITLE
Can't import the named export 'AlwaysDepth' from non EcmaScript module (only default export is available)

### ISSUE THREAD

**Issue by asjustis** [pmndrs/react-postprocessing#114]
Hi,

Sorry for repeating the ticket with the same name, but looks like with the `postprocessing@6.24.0` recent release, @[vanruesc](https://github.com/vanruesc) did some breaking changes to cause this issue again ( https://github.com/vanruesc/postprocessing/issues/312 ).

When I install packages with YARN, `react-postprocessing` goes to using the `postprocessing@^6.23.3` version which results in installing the @6.24.0, therefore I cannot publish builds anymore, and I'm already late :D 

Should this be fixed from `react-postprocessing` side, or can I fix it somehow with yarn.lock myself?

Thanks,
Justinas

**Comment by vanruesc** [comment]
The bundle extension was changed to `.mjs` in `6.24.0` because the package type of `three` was changed to `module` in r137, causing issues with Ava.js testing. [This comment](https://github.com/facebook/create-react-app/issues/10356#issuecomment-1000016251) suggests that CRA 5.0.0 can now handle `.mjs` bundles which prompted me to try again.

However, the Webpack issues remained and the bundle name change was reverted in `6.24.1`. See https://github.com/vanruesc/postprocessing/issues/346.

**Comment by drcmda** [comment]
@asjustis i updated to 6.24.1

**Comment by asjustis** [comment]
🙏  Thank you guys. In the meantime I changed my yarn.lock for specific version, but that's temporary. This should fix it properly.
