### ISSUE TITLE
Memory Leak | Bloom

### ISSUE THREAD

**Issue by pixelass** [pmndrs/react-postprocessing#132]
As described in #68 there's a memory leak when updating the intensity of `Bloom`

Here's our reproduction: 

https://codesandbox.io/s/mystifying-kare-k4lh3b?file=/src/App.js

```js
useFrame(() => {
  if (bloomRef.current && intensityRef.current) {
      bloomRef.current.intensity = intensityRef.current;
  }
});
```

Screencast: (Activity Monitor > View > Update Frequency > Very Often (1sec)

![Bloom_Memory_Leak](https://user-images.githubusercontent.com/1148334/170448935-d7adc200-31f2-4b8e-8ae2-768796c52967.gif)

**Comment by chasedavis** [comment]
maybe related discussion/cause [here](https://discord.com/channels/740090768164651008/952231094546219111/988533419510235217)

**Comment by cmrnfaith** [comment]
Was there ever a solution created for this issue? I am running into the same issue within my project.

**Comment by chasedavis** [comment]
> Was there ever a solution created for this issue? I am running into the same issue within my project.

Not to my knowledge. If you use postprocessing directly it's avoidable though.

**Comment by chasedavis** [comment]
@max-hans this library (react-postprocessing) is a thin react abstraction over [postprocessing](https://github.com/pmndrs/postprocessing). If you use postprocessing API's directly instead of this library you will likely not run into this issue (but will also have to do lifecycle management yourself).
