### ISSUE TITLE
Update peer dependency range to match postprocessing?

### ISSUE THREAD

**Issue by gouldingken** [pmndrs/react-postprocessing#175]
It looks like postprocessing does not support three 0.149.0 yet. It may be helpful to update the peer dependency range here - or note it in the docs.

```
└─┬ @react-three/postprocessing 2.7.0
  └─┬ postprocessing 6.29.3
    └── ✕ unmet peer three@">= 0.125.0 < 0.149.0": found 0.149.0
```

**Comment by webprofusion-chrisc** [comment]
Just as additional info for this, currently running create-react-app and installing `three`,  `@react-three/fiber` and 
`@react-three/postprocessing` results in an app that doesn't build. Instead you have to bump three down to 0.148.x

Could the upper bound on the dependency version be removed or alternatively the upper bound for the @react-three/fiber three dependency be set to match. Just so that out of the box installs work.

**Comment by talentlessguy** [comment]
could you please submit a PR with pinned peer dep version?

**Comment by talentlessguy** [comment]
It's done now, `three` is set to `>= 0.138.0 < 0.152.0`
