### ISSUE TITLE
DepthOfField focusDistance doesn't seem to work (possibly renamed to focus?)

### ISSUE THREAD

**Issue by aVileBroker** [pmndrs/react-postprocessing#46]
I've tried it on a couple of projects hoping to get it working but it seems to be fixed to some default range of around 1 meter

```
<DepthOfField
  focusDistance={5} // it doesn't change no matter what is passed here
  focalLength={0.1}
  bokehScale={5}
/>
```

~The blobs example in this project has a focusDistance of 0, and codesandbox seems to be down at the moment so I can't test it on the example.~ codesandbox is back and it DOES work in the demo - so this is probably user error... Though I've tried it with a orthographic and perspective camera with no success
Blobs: https://codesandbox.io/s/m94xb

~Here's the DepthOfField example from postprocessing which does work, but the property is called "focus" instead of "focusDistance" so I wonder if it just wasn't updated in this package.~ https://vanruesc.github.io/postprocessing/public/demo/#depth-of-field

~If that's the case I'd be happy to make a PR to update~

I pushed an example of the failing repo (sorry if it's a bit of a mess) - here's the link: https://github.com/aVileBroker/Isometric-City

**Comment by aVileBroker** [comment]
As a test I updated the blobs demo to the highest versions of the respective packages, as well as my own repo to the same. Still no luck in my repo - and the blobs demo broke after RTF was upgraded past the beta version it was on. (to 5.0.1)

Still, the behavior I see is that at focusDistance of 0, I can get close to the cube and it will be sharp around .25 meters away with a focalLength of .02. Anything other than 0 will never be fully in focus.

The react-three-gui box I had for updating the focalDistance to test doesn't seem to do anything, and it seems like the DepthOfField component doesn't update the effect when the props change, which makes it a bit harder to debug.

**Comment by aVileBroker** [comment]
Codesandbox to make it easier to reproduce: https://codesandbox.io/s/distracted-chatelet-bev0r?file=/src/App.js

**Comment by gsimone** [comment]
https://codesandbox.io/s/young-water-du0dz?file=/src/App.js here's the reworked sandbox.
I'm using an effect to couple the dof target to the the cube. This is the easiest way to actually keep an object in focus when the camera moves. 

Otherwise, the focusDistance and focusLength are relative the depth buffer. focusDistance goes from 0 to 1, a value of 0 will focus everything that is at 0 depth (ie close to the near plane).

Focus length (0 -1 ) is an additional depth that will be in focus around (before and after) your focus distance.

If you play with the demo here https://vanruesc.github.io/postprocessing/public/demo/#depth-of-field
and set focus (which is actually focusDistance in the demo code) to 0 and length to 0.5, your focus will start on the plant, continue to half of the depth (the second plant) and then gradually blur out.

Keep in mind that the depth buffer depends on your camera near and far plane.

**Comment by aVileBroker** [comment]
Aha! That's exactly what I was missing. So I need to setup a target to measure how far into the depth buffer I'm trying to keep in focus.

Thanks a ton. I'm also a photo/videographer/3d modeller and am used to setting focus based on physical distances so I'll just need to set up some basic targeting to get this working how my brain wants it too :D
